### ISSUE TITLE
磁盘写入太频繁了, 能听到机械硬盘每一秒钟就启动一次

### ISSUE THREAD

**Issue by czy1238677** [newdraw/AppTime#2]
希望能修改磁盘写入频率,  比如5分钟写入一次或者提供磁盘写入频率的设置选项

**Comment by newdraw** [comment]
感谢反馈，近期解决。

**Comment by newdraw** [comment]
你好，已经解决。

请利用“**设置->磁盘缓存**”调整写入频率。其最大值50MB，可能将写入频率降低到10分钟/次。

### 新版下载
下载[Release.zip](https://github.com/newdraw/AppTime/raw/master/Release%20v0.11.zip)，解压到任意目录； 

### 升级注意
如需升级老版本的AppTime，请解压覆盖到老版本目录，但请不要覆盖data.db文件。
