### ISSUE TITLE
你好，可以更新一个包含开发环境的版本、部署编译源码的README吗，想二次开发，但部署时遇到了一些问题

### ISSUE THREAD

**Issue by weingxing** [newdraw/AppTime#3]
你好，可以更新一个包含开发环境的版本、部署编译源码的README吗，想二次开发，但部署时遇到了一些问题

**Comment by newdraw** [comment]
你好。开发环境Visual Studio 2019，.NET Framework 4.8。发布的时候请把源码里的webui目录复制到exe所在目录。
有具体问题可以交流。

**Comment by weingxing** [comment]
好的，已经成功编译，感谢
