### ISSUE TITLE
是否有开机自启动？

### ISSUE THREAD

**Issue by JunerLee** [newdraw/AppTime#5]

**Comment by JunerLee** [comment]
是否考虑开机自启动选项？谢谢

**Comment by newdraw** [comment]
可以啊，近期发一个版本。

**Comment by newdraw** [comment]
你好，请更新到v0.12版本：
![image](https://user-images.githubusercontent.com/48037916/109314002-c53b9f80-7883-11eb-87d0-7c111ebbf90a.png)
